---
apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: test-one
spec:
  git:
    url: https://github.com/trisberg/test-include-ignore.git
    ref:
      branch: main
    subPath: test-one
    ignore: |
      # exclude all but test-one
      /*
      !/test-one
---
apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: test-two
spec:
  git:
    url: https://github.com/trisberg/test-include-ignore.git
    ref:
      branch: main
    subPath: test-two
    ignore: |
      # exclude all but test-two
      /*
      !/test-two
